version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      container_name: ecom-mysql
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # Opcional: Se você tem um script SQL para inicializar o banco, descomente a linha abaixo
      # - ./path/to/your/script.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always

volumes:
  mysql-data:
    driver: local
